# Generated by Django 3.2.5 on 2021-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user_id', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'form',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('responses', models.TextField()),
                ('user_id', models.CharField(max_length=50)),
                ('form_id', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'form_response',
                'managed': True,
            },
        ),
    ]
